steps:
  # 0. Create a URL-safe tag from the branch name
  - name: "bash"
    id: "Create Tag"
    args:
      - "-c"
      - |
        echo $BRANCH_NAME | sed 's/\//-/g' > _TAG_NAME

  # --- BACKEND SECTION ---
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Backend"
    args:
      [
        "build",
        "--target",
        "development",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/nxtturn-images/backend-dev:latest",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "Push Backend"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/nxtturn-images/backend-dev:latest",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Backend"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "$BRANCH_NAME" == "dev" ]; then
          gcloud run deploy nxtturn-backend-dev \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/nxtturn-images/backend-dev:latest \
            --region us-central1 \
            --tag=$(cat _TAG_NAME) \
            --service-account nxtturn-dev-cloud-robot@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars ENVIRONMENT=development,IS_LOCAL=False,GS_BUCKET_NAME=nxtturn-media-dev-cloud,FRONTEND_URL=https://dev.nxtturn.com,BACKEND_URL=https://nxtturn-backend-dev-656842361738.us-central1.run.app,EMAIL_MODE=brevo \
            --set-secrets "DATABASE_URL=DATABASE_CONNECTION_NAME:latest,SECRET_KEY=SECRET_KEY:latest,DB_PASSWORD=DB_PASSWORD:latest,REDIS_URL=REDIS_URL:latest,BREVO_API_KEY=BREVO_API_KEY:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest" \
            --allow-unauthenticated
        else
          gcloud run deploy nxtturn-backend-dev \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/nxtturn-images/backend-dev:latest \
            --region us-central1 \
            --no-traffic \
            --tag=$(cat _TAG_NAME) \
            --service-account nxtturn-dev-cloud-robot@$PROJECT_ID.iam.gserviceaccount.com \
            --set-env-vars ENVIRONMENT=development,IS_LOCAL=False,GS_BUCKET_NAME=nxtturn-media-dev-cloud,FRONTEND_URL=https://dev.nxtturn.com,BACKEND_URL=https://nxtturn-backend-dev-656842361738.us-central1.run.app,EMAIL_MODE=brevo \
            --set-secrets "DATABASE_URL=DATABASE_CONNECTION_NAME:latest,SECRET_KEY=SECRET_KEY:latest,DB_PASSWORD=DB_PASSWORD:latest,REDIS_URL=REDIS_URL:latest,BREVO_API_KEY=BREVO_API_KEY:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest" \
            --allow-unauthenticated
        fi

  # --- FRONTEND SECTION ---
  - name: "gcr.io/cloud-builders/docker"
    id: "Build Frontend"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build --build-arg VITE_GOOGLE_CLIENT_ID=$$GOOGLE_ID --build-arg VITE_API_BASE_URL=/api/ --build-arg VITE_WS_BASE_URL=/ws/ --build-arg VITE_AD_MODE=mock -f frontend/Dockerfile -t us-central1-docker.pkg.dev/$PROJECT_ID/nxtturn-images/frontend-dev:latest ./frontend
    secretEnv: ["GOOGLE_ID"]

  - name: "gcr.io/cloud-builders/docker"
    id: "Push Frontend"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/nxtturn-images/frontend-dev:latest",
      ]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy Frontend"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [ "$BRANCH_NAME" == "dev" ]; then
          gcloud run deploy nxtturn-frontend-dev \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/nxtturn-images/frontend-dev:latest \
            --region us-central1 \
            --tag=$(cat _TAG_NAME) \
            --allow-unauthenticated
        else
          gcloud run deploy nxtturn-frontend-dev \
            --image us-central1-docker.pkg.dev/$PROJECT_ID/nxtturn-images/frontend-dev:latest \
            --region us-central1 \
            --no-traffic \
            --tag=$(cat _TAG_NAME) \
            --allow-unauthenticated
        fi

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/nxtturn-images/backend-dev:latest"
  - "us-central1-docker.pkg.dev/$PROJECT_ID/nxtturn-images/frontend-dev:latest"

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID/versions/latest
      env: "GOOGLE_ID"
