# Generated by Django 5.2 on 2026-07-02 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('exam_code', models.CharField(max_length=50)),
                ('exam_name', models.CharField(max_length=255)),
                ('exam_year', models.PositiveIntegerField()),
                ('conducting_body', models.CharField(max_length=255)),
                ('exam_category', models.CharField(max_length=100)),
                ('estimated_time_hours', models.IntegerField()),
            ],
            options={
                'db_table': 'exam',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.CharField(blank=True, max_length=50, null=True)),
                ('difficulty_level', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('question_text', models.TextField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='jee_question_images/')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('chapter', models.ForeignKey(blank=True, db_column='chapter_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='MockAdmin.chapter')),
                ('exam', models.ForeignKey(blank=True, db_column='exam_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='MockAdmin.exam')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnalytics',
            fields=[
                ('question', models.OneToOneField(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MockAdmin.question')),
                ('total_attempts', models.IntegerField(default=0)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('wrong_attempts', models.IntegerField(default=0)),
                ('skipped_attempts', models.IntegerField(default=0)),
                ('avg_time_sec', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('accuracy_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'db_table': 'question_analytics',
            },
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_value', models.CharField(max_length=10)),
                ('answer_type', models.CharField(max_length=50)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='MockAdmin.question')),
            ],
            options={
                'db_table': 'correct_answer',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_A', models.TextField()),
                ('option_B', models.TextField()),
                ('option_C', models.TextField()),
                ('option_D', models.TextField()),
                ('option_A_images', models.JSONField(blank=True, default=dict, null=True)),
                ('option_B_images', models.JSONField(blank=True, default=dict, null=True)),
                ('option_C_images', models.JSONField(blank=True, default=dict, null=True)),
                ('option_D_images', models.JSONField(blank=True, default=dict, null=True)),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='MockAdmin.question')),
            ],
            options={
                'db_table': 'question_option',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('solution_id', models.AutoField(primary_key=True, serialize=False)),
                ('explaination_text', models.TextField()),
                ('image_url', models.JSONField(default=dict)),
                ('hints', models.TextField()),
                ('question', models.ForeignKey(db_column='question_id', on_delete=django.db.models.deletion.CASCADE, to='MockAdmin.question')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solution',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('exam', models.ForeignKey(db_column='exam_id', on_delete=django.db.models.deletion.CASCADE, to='MockAdmin.exam')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(blank=True, db_column='subject_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='MockAdmin.subject'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(db_column='subject_id', on_delete=django.db.models.deletion.CASCADE, to='MockAdmin.subject'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_name', models.CharField(max_length=255)),
                ('chapter', models.ForeignKey(db_column='chapter_id', on_delete=django.db.models.deletion.CASCADE, to='MockAdmin.chapter')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, db_column='topic_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='MockAdmin.topic'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('subject', 'question_type', 'question_text'), name='unique_question_per_subject_type'),
        ),
    ]
