# Generated by Django 5.2 on 2026-08-03 05:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("board_id", models.AutoField(primary_key=True, serialize=False)),
                ("board_name", models.CharField(max_length=255)),
                ("board_code", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "boards",
            },
        ),
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                (
                    "education_level_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("education_level", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "education_levels",
            },
        ),
        migrations.CreateModel(
            name="EntranceExamCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "entrance_exam_categories",
            },
        ),
        migrations.CreateModel(
            name="ExamLevel",
            fields=[
                ("level_id", models.AutoField(primary_key=True, serialize=False)),
                ("level_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "exam_levels",
            },
        ),
        migrations.CreateModel(
            name="ExamType",
            fields=[
                ("exam_type_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "exam_types",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("feedback_id", models.AutoField(primary_key=True, serialize=False)),
                ("stars", models.PositiveSmallIntegerField()),
                ("feedback_text", models.TextField(blank=True, null=True)),
                ("rated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "feedback",
            },
        ),
        migrations.CreateModel(
            name="Field",
            fields=[
                ("field_id", models.AutoField(primary_key=True, serialize=False)),
                ("field_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "fields",
            },
        ),
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "job_category_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("job_category_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "job_category",
            },
        ),
        migrations.CreateModel(
            name="JobExamCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "job_exam_categories",
            },
        ),
        migrations.CreateModel(
            name="QuestionReport",
            fields=[
                ("report_id", models.AutoField(primary_key=True, serialize=False)),
                ("reason", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="Pending", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "question_reports",
            },
        ),
        migrations.CreateModel(
            name="SchoolExamCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "school_exam_categories",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("state_id", models.AutoField(primary_key=True, serialize=False)),
                ("state_name", models.CharField(max_length=100)),
                ("state_code", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "states",
            },
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                ("stream_id", models.AutoField(primary_key=True, serialize=False)),
                ("stream_name", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "streams",
            },
        ),
        migrations.CreateModel(
            name="SubField",
            fields=[
                ("sub_field_id", models.AutoField(primary_key=True, serialize=False)),
                ("sub_field_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "sub_fields",
            },
        ),
        migrations.CreateModel(
            name="TestDefinition",
            fields=[
                ("test_id", models.AutoField(primary_key=True, serialize=False)),
                ("test_name", models.CharField(max_length=255)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("Practice", "Practice"),
                            ("Custom", "Custom"),
                            ("Mock", "Mock"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "total_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "negative_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "test_definitions",
            },
        ),
        migrations.CreateModel(
            name="TestSession",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("In Progress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="In Progress",
                        max_length=20,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("rank", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "test_sessions",
            },
        ),
        migrations.RemoveField(
            model_name="topic",
            name="chapter",
        ),
        migrations.RemoveField(
            model_name="question",
            name="topic",
        ),
        migrations.RemoveConstraint(
            model_name="question",
            name="unique_question_per_subject_type",
        ),
        migrations.RenameField(
            model_name="correctanswer",
            old_name="answer_id",
            new_name="correct_answer_id",
        ),
        migrations.RenameField(
            model_name="correctanswer",
            old_name="answer_value",
            new_name="option_id",
        ),
        migrations.RenameField(
            model_name="questionanalytics",
            old_name="avg_time_sec",
            new_name="avg_time_taken",
        ),
        migrations.RenameField(
            model_name="questionoption",
            old_name="option_A",
            new_name="option_a",
        ),
        migrations.RenameField(
            model_name="questionoption",
            old_name="option_B",
            new_name="option_b",
        ),
        migrations.RenameField(
            model_name="questionoption",
            old_name="option_C",
            new_name="option_c",
        ),
        migrations.RenameField(
            model_name="questionoption",
            old_name="option_D",
            new_name="option_d",
        ),
        migrations.RemoveField(
            model_name="correctanswer",
            name="answer_type",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="estimated_time_hours",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="exam_category",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="exam_year",
        ),
        migrations.RemoveField(
            model_name="question",
            name="language",
        ),
        migrations.RemoveField(
            model_name="question",
            name="status",
        ),
        migrations.RemoveField(
            model_name="question",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="questionoption",
            name="option_A_images",
        ),
        migrations.RemoveField(
            model_name="questionoption",
            name="option_B_images",
        ),
        migrations.RemoveField(
            model_name="questionoption",
            name="option_C_images",
        ),
        migrations.RemoveField(
            model_name="questionoption",
            name="option_D_images",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="teacher",
        ),
        migrations.AddField(
            model_name="chapter",
            name="chapter_order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chapter",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="category_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="exam",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="exam_pattern",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="question",
            name="hint",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="question",
            name="marks",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="negative_marks",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="questionanalytics",
            name="difficulty_index",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="questionanalytics",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="option_e",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solution",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="exam",
            name="conducting_body",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exam",
            name="exam_code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
        migrations.AlterField(
            model_name="solution",
            name="image_url",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterModelTable(
            name="chapter",
            table="chapters",
        ),
        migrations.AlterModelTable(
            name="correctanswer",
            table="correct_answers",
        ),
        migrations.AlterModelTable(
            name="exam",
            table="exams",
        ),
        migrations.AlterModelTable(
            name="question",
            table="questions",
        ),
        migrations.AlterModelTable(
            name="questionoption",
            table="question_options",
        ),
        migrations.AlterModelTable(
            name="subject",
            table="subjects",
        ),
        migrations.AddField(
            model_name="exam",
            name="board",
            field=models.ForeignKey(
                blank=True,
                db_column="board_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MockAdmin.board",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="education_level",
            field=models.ForeignKey(
                blank=True,
                db_column="education_level_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MockAdmin.educationlevel",
            ),
        ),
        migrations.AddField(
            model_name="entranceexamcategory",
            name="education_level",
            field=models.ForeignKey(
                db_column="education_level_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.educationlevel",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="level",
            field=models.ForeignKey(
                blank=True,
                db_column="level_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MockAdmin.examlevel",
            ),
        ),
        migrations.AddField(
            model_name="entranceexamcategory",
            name="exam_type",
            field=models.ForeignKey(
                db_column="exam_type_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.examtype",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="exam_type",
            field=models.ForeignKey(
                blank=True,
                db_column="exam_type_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MockAdmin.examtype",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="field",
            field=models.ForeignKey(
                blank=True,
                db_column="field_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MockAdmin.field",
            ),
        ),
        migrations.AddField(
            model_name="jobexamcategory",
            name="exam_type",
            field=models.ForeignKey(
                db_column="exam_type_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.examtype",
            ),
        ),
        migrations.AddField(
            model_name="jobexamcategory",
            name="job_category",
            field=models.ForeignKey(
                db_column="job_category_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.jobcategory",
            ),
        ),
        migrations.AddField(
            model_name="questionreport",
            name="question",
            field=models.ForeignKey(
                db_column="question_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.question",
            ),
        ),
        migrations.AddField(
            model_name="questionreport",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schoolexamcategory",
            name="education_level",
            field=models.ForeignKey(
                db_column="education_level_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.educationlevel",
            ),
        ),
        migrations.AddField(
            model_name="schoolexamcategory",
            name="exam_type",
            field=models.ForeignKey(
                db_column="exam_type_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.examtype",
            ),
        ),
        migrations.AddField(
            model_name="board",
            name="state",
            field=models.ForeignKey(
                db_column="state_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.state",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="state",
            field=models.ForeignKey(
                blank=True,
                db_column="state_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MockAdmin.state",
            ),
        ),
        migrations.AddField(
            model_name="field",
            name="stream",
            field=models.ForeignKey(
                db_column="stream_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.stream",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                db_column="stream_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MockAdmin.stream",
            ),
        ),
        migrations.AddField(
            model_name="subfield",
            name="field",
            field=models.ForeignKey(
                db_column="field_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.field",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="sub_field",
            field=models.ForeignKey(
                blank=True,
                db_column="sub_field_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MockAdmin.subfield",
            ),
        ),
        migrations.AddField(
            model_name="testdefinition",
            name="exam",
            field=models.ForeignKey(
                db_column="exam_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.exam",
            ),
        ),
        migrations.AddField(
            model_name="testsession",
            name="test",
            field=models.ForeignKey(
                db_column="test_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.testdefinition",
            ),
        ),
        migrations.AddField(
            model_name="testsession",
            name="user",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="questionreport",
            name="session",
            field=models.ForeignKey(
                blank=True,
                db_column="session_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MockAdmin.testsession",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="result",
            field=models.ForeignKey(
                db_column="result_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.testsession",
            ),
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
