# Generated by Django 5.2 on 2026-08-05 07:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "MockAdmin",
            "0002_board_educationlevel_entranceexamcategory_examlevel_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_previousyear",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testdefinition",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_column="user_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MockExam",
            fields=[
                ("mockexam_id", models.AutoField(primary_key=True, serialize=False)),
                ("mockexam_name", models.CharField(max_length=255)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "total_marks",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam",
                    models.ForeignKey(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MockAdmin.exam",
                    ),
                ),
            ],
            options={
                "db_table": "mockexams",
            },
        ),
        migrations.AddField(
            model_name="testdefinition",
            name="mockexam",
            field=models.ForeignKey(
                blank=True,
                db_column="mockexam_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="MockAdmin.mockexam",
            ),
        ),
    ]
