# Generated by Django 5.2 on 2026-08-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0003_question_is_previousyear_testdefinition_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="education_level",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="stream",
        ),
        migrations.AddField(
            model_name="exam",
            name="education_levels",
            field=models.ManyToManyField(
                blank=True, related_name="exams", to="MockAdmin.educationlevel"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="streams",
            field=models.ManyToManyField(
                blank=True, related_name="exams", to="MockAdmin.stream"
            ),
        ),
    ]
