# Generated by Django 5.2 on 2026-08-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0004_remove_exam_education_level_remove_exam_stream_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="logo",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
