# Generated by Django 5.2 on 2026-08-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0005_exam_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_trending",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="exam",
            name="trending_score",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
