# Generated by Django 5.2 on 2026-08-11 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0006_exam_is_trending_exam_trending_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                db_column="exam_code",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.exam",
            ),
        ),
    ]
