# Generated by Django 5.2 on 2026-08-11 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0007_alter_question_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="mock_exam",
            field=models.ForeignKey(
                blank=True,
                db_column="mockexam_name",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.mockexam",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                blank=True,
                db_column="exam_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MockAdmin.exam",
            ),
        ),
    ]
