# Generated by Django 5.2 on 2026-08-12 05:55
# FIXED: the auto-generated AlterField below did a bare `::jsonb` cast on
# Question.image_url, which fails the moment any existing row has ''
# (ImageField's empty default) or a plain file path like
# 'question_images/foo.png' — neither is valid JSON, hence:
#   django.db.utils.DataError: invalid input syntax for type json
# Replaced with RunSQL that converts each row explicitly instead of
# casting blindly:
#   - NULL / empty string          -> '{}'::jsonb
#   - an existing file path/string -> {"images": ["<that path>"]}
#     (so any previously-imported images aren't silently thrown away)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0008_question_mock_exam_alter_question_exam"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionoption",
            name="option_images",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE questions
                ALTER COLUMN image_url TYPE jsonb
                USING (
                    CASE
                        WHEN image_url IS NULL OR image_url = '' THEN '{}'::jsonb
                        ELSE jsonb_build_object('images', jsonb_build_array(image_url))
                    END
                );
                ALTER TABLE questions ALTER COLUMN image_url SET DEFAULT '{}'::jsonb;
            """,
            reverse_sql="""
                ALTER TABLE questions
                ALTER COLUMN image_url TYPE varchar(100)
                USING (
                    CASE
                        WHEN image_url = '{}'::jsonb THEN NULL
                        ELSE (image_url -> 'images' ->> 0)
                    END
                );
                ALTER TABLE questions ALTER COLUMN image_url DROP DEFAULT;
            """,
        ),
    ]