# Generated by Django 5.2 on 2026-08-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0009_questionoption_option_images_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Under Review"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="image_url",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
