# Generated by Django 5.2 on 2026-08-17 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0010_exam_status_alter_question_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("board_name", models.CharField(max_length=255)),
                (
                    "applicable_region",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Review", "Review"),
                            ("Inactive", "Inactive"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_boards",
                        to="MockAdmin.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exam_board_associations",
            },
        ),
        migrations.CreateModel(
            name="ExamDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_limit", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "application_mode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("exam_mode", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "exam_frequency",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("total_marks", models.IntegerField(blank=True, null=True)),
                (
                    "negative_marking",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "official_website",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "helpline_contact",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "exam",
                    models.OneToOneField(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detail",
                        to="MockAdmin.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exam_details",
            },
        ),
        migrations.CreateModel(
            name="ExamEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("educational_qualification", models.TextField(blank=True, null=True)),
                (
                    "minimum_marks",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "age_criteria",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "other_conditions",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "exam",
                    models.OneToOneField(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibility_detail",
                        to="MockAdmin.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exam_eligibility",
            },
        ),
        migrations.CreateModel(
            name="ExamImportantDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_start", models.DateField(blank=True, null=True)),
                ("application_end", models.DateField(blank=True, null=True)),
                ("admit_card_release", models.DateField(blank=True, null=True)),
                ("exam_date", models.DateField(blank=True, null=True)),
                ("result_date", models.DateField(blank=True, null=True)),
                (
                    "exam",
                    models.OneToOneField(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="important_dates",
                        to="MockAdmin.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exam_important_dates",
            },
        ),
        migrations.CreateModel(
            name="ExamPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "negative_marking",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "marking_scheme",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("unattempted", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "exam",
                    models.OneToOneField(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pattern",
                        to="MockAdmin.exam",
                    ),
                ),
            ],
            options={
                "db_table": "exam_patterns",
            },
        ),
        migrations.CreateModel(
            name="ExamPatternSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section_name", models.CharField(max_length=100)),
                ("questions", models.IntegerField(default=0)),
                ("marks", models.IntegerField(default=0)),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("section_order", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "exam_pattern",
                    models.ForeignKey(
                        db_column="exam_pattern_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="MockAdmin.exampattern",
                    ),
                ),
            ],
            options={
                "db_table": "exam_pattern_sections",
                "ordering": ["section_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                ("topic_id", models.AutoField(primary_key=True, serialize=False)),
                ("topic_name", models.CharField(max_length=255)),
                ("topic_order", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        db_column="chapter_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="MockAdmin.chapter",
                    ),
                ),
            ],
            options={
                "db_table": "topics",
            },
        ),
    ]
