# Generated by Django 5.2 on 2026-08-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0011_examboard_examdetail_exameligibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="examtype",
            name="education_levels",
            field=models.ManyToManyField(
                blank=True, related_name="exam_types", to="MockAdmin.educationlevel"
            ),
        ),
    ]
