# Generated by Django 5.2 on 2026-08-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0012_examtype_education_levels"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examdetail",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="exameligibility",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="examimportantdate",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="exampattern",
            name="exam",
        ),
        migrations.RemoveField(
            model_name="exampatternsection",
            name="exam_pattern",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="chapter",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="status",
        ),
        migrations.RemoveField(
            model_name="examtype",
            name="education_levels",
        ),
        migrations.RemoveField(
            model_name="questionoption",
            name="option_images",
        ),
        migrations.AlterField(
            model_name="question",
            name="image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
        migrations.DeleteModel(
            name="ExamBoard",
        ),
        migrations.DeleteModel(
            name="ExamDetail",
        ),
        migrations.DeleteModel(
            name="ExamEligibility",
        ),
        migrations.DeleteModel(
            name="ExamImportantDate",
        ),
        migrations.DeleteModel(
            name="ExamPattern",
        ),
        migrations.DeleteModel(
            name="ExamPatternSection",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
