# Generated by Django 5.2 on 2026-08-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "MockAdmin",
            "0013_remove_examdetail_exam_remove_exameligibility_exam_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="examtype",
            name="education_levels",
            field=models.ManyToManyField(
                blank=True, related_name="exam_types", to="MockAdmin.educationlevel"
            ),
        ),
    ]
