# Generated by Django 5.2 on 2026-08-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0014_examtype_education_levels"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionoption",
            name="option_images",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
