from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MockAdmin', '0015_questionoption_option_images'),
    ]

    operations = [
        # CHANGED: the autogenerated AlterField tried a straight
        # `image_url::json` cast, which failed because existing rows
        # hold plain file-path strings (e.g.
        # "jee_question_images/organic-chemistry-....-q5."), not valid
        # JSON text. RunSQL with a USING clause wraps any existing
        # non-empty string into {"images": ["<old value>"]} so old data
        # survives the migration instead of blocking it. state_operations
        # keeps Django's model state in sync even though the SQL is custom.
        migrations.RunSQL(
            sql="""
                ALTER TABLE questions
                ALTER COLUMN image_url TYPE jsonb
                USING (
                    CASE
                        WHEN image_url IS NULL OR image_url = '' THEN '{}'::jsonb
                        ELSE jsonb_build_object('images', jsonb_build_array(image_url))
                    END
                );
                ALTER TABLE questions ALTER COLUMN image_url SET DEFAULT '{}'::jsonb;
            """,
            reverse_sql="""
                ALTER TABLE questions
                ALTER COLUMN image_url TYPE varchar(255)
                USING (image_url->>'images'->>0);
                ALTER TABLE questions ALTER COLUMN image_url DROP DEFAULT;
            """,
            state_operations=[
                migrations.AlterField(
                    model_name='question',
                    name='image_url',
                    field=models.JSONField(default=dict, null=True, blank=True),
                ),
            ],
        ),
    ]