# Generated by Django 5.2 on 2026-08-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0016_alter_question_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="correctanswer",
            name="option_id",
            field=models.TextField(),
        ),
    ]
