# Generated by Django 5.2 on 2026-08-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0017_alter_correctanswer_option_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="mockexam",
            name="pattern",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
