# Generated by Django 5.2 on 2026-09-01 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0018_mockexam_pattern"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="pyq_exam",
            field=models.ForeignKey(
                blank=True,
                db_column="pyq_exam_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pyq_questions",
                to="MockAdmin.exam",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="pyq_session",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="pyq_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
