# Generated by Django 5.2 on 2026-09-23 06:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0019_question_pyq_exam_question_pyq_session_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionChapterMapping",
            fields=[
                ("mapping_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_primary", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ai", "AI"),
                            ("rules", "Rules"),
                            ("manual", "Manual"),
                            ("legacy", "Legacy"),
                        ],
                        default="ai",
                        max_length=20,
                    ),
                ),
                ("confidence", models.SmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "chapter",
                    models.ForeignKey(
                        db_column="chapter_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_mappings",
                        to="MockAdmin.chapter",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapter_mappings",
                        to="MockAdmin.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_chapter_mappings",
                "unique_together": {("question", "chapter")},
            },
        ),
    ]
