# Generated by Django 5.2 on 2026-09-28 07:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0020_add_question_chapter_mapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardChapter",
            fields=[
                (
                    "standard_chapter_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "standard_chapters",
                "unique_together": {("subject_name", "name")},
            },
        ),
        migrations.AddField(
            model_name="chapter",
            name="standard_chapter",
            field=models.ForeignKey(
                blank=True,
                db_column="standard_chapter_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chapters",
                to="MockAdmin.standardchapter",
            ),
        ),
        migrations.CreateModel(
            name="QuestionOccurrence",
            fields=[
                ("occurrence_id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("session", models.CharField(blank=True, default="", max_length=50)),
                ("paper", models.CharField(blank=True, default="", max_length=50)),
                ("question_number", models.PositiveIntegerField(blank=True, null=True)),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source_file",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "source_chapter_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("match_type", models.CharField(default="new", max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "exam",
                    models.ForeignKey(
                        db_column="exam_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_occurrences",
                        to="MockAdmin.exam",
                    ),
                ),
                (
                    "mock_exam",
                    models.ForeignKey(
                        blank=True,
                        db_column="mockexam_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="occurrences",
                        to="MockAdmin.mockexam",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occurrences",
                        to="MockAdmin.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_occurrences",
                "indexes": [
                    models.Index(
                        fields=["exam", "year", "session"],
                        name="question_oc_exam_id_402282_idx",
                    )
                ],
                "unique_together": {
                    ("question", "exam", "year", "session", "paper", "question_number")
                },
            },
        ),
        migrations.CreateModel(
            name="QuestionTag",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[("topic", "Topic"), ("concept", "Concept")],
                        max_length=10,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("source", models.CharField(default="rules", max_length=20)),
                ("confidence", models.SmallIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="MockAdmin.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_tags",
                "unique_together": {("question", "kind", "label")},
            },
        ),
    ]
