# Generated by Django 5.2 on 2026-09-28 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0021_standardchapter_chapter_standard_chapter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="content_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="similar_to",
            field=models.ForeignKey(
                blank=True,
                db_column="similar_to_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="similar_questions",
                to="MockAdmin.question",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="stem_key",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=24
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="text_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
