# Generated by Django 5.2 on 2026-09-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0022_question_content_hash_question_similar_to_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="questiontag",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="questiontag",
            name="question",
        ),
        migrations.AlterUniqueTogether(
            name="standardchapter",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="standard_chapter",
        ),
        migrations.RemoveField(
            model_name="question",
            name="content_hash",
        ),
        migrations.RemoveField(
            model_name="question",
            name="similar_to",
        ),
        migrations.RemoveField(
            model_name="question",
            name="stem_key",
        ),
        migrations.RemoveField(
            model_name="question",
            name="text_hash",
        ),
        migrations.DeleteModel(
            name="QuestionOccurrence",
        ),
        migrations.DeleteModel(
            name="QuestionTag",
        ),
        migrations.DeleteModel(
            name="StandardChapter",
        ),
    ]
