# Generated by Django 5.2 on 2026-09-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MockAdmin", "0023_alter_questiontag_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="appearances",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="question",
            name="content_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="is_custom",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="is_mock",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="is_practice",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="text_hash",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
