# Generated by Django 5.2 on 2026-07-02 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("avatar_url", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_answer", models.TextField()),
                ("is_correct", models.BooleanField(default=False)),
                ("teacher_feedback", models.TextField(blank=True, null=True)),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MockAdmin.question",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserQuestionAttempt",
            fields=[
                ("attempt_id", models.AutoField(primary_key=True, serialize=False)),
                ("selected_ans", models.CharField(max_length=20)),
                ("is_correct", models.BooleanField(default=False)),
                ("time_taken_sec", models.IntegerField()),
                ("marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("negative_marks", models.DecimalField(decimal_places=2, max_digits=5)),
                ("marked_for_review", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MockAdmin.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_question_attempt",
            },
        ),
    ]
