# Generated by Django 5.2 on 2026-07-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MockStudent", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="student",
            table="mockups_student",
        ),
        migrations.AlterModelTable(
            name="studentsubmission",
            table="mockups_studentsubmission",
        ),
    ]
