# Generated by Django 5.2 on 2026-08-03 05:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "MockAdmin",
            "0002_board_educationlevel_entranceexamcategory_examlevel_and_more",
        ),
        ("MockStudent", "0002_alter_student_table_alter_studentsubmission_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userquestionattempt",
            name="marked_for_review",
        ),
        migrations.RemoveField(
            model_name="userquestionattempt",
            name="marks",
        ),
        migrations.RemoveField(
            model_name="userquestionattempt",
            name="negative_marks",
        ),
        migrations.RemoveField(
            model_name="userquestionattempt",
            name="selected_ans",
        ),
        migrations.RemoveField(
            model_name="userquestionattempt",
            name="time_taken_sec",
        ),
        migrations.RemoveField(
            model_name="userquestionattempt",
            name="user",
        ),
        migrations.AddField(
            model_name="userquestionattempt",
            name="attempted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userquestionattempt",
            name="marks_obtained",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="userquestionattempt",
            name="selected_option_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="userquestionattempt",
            name="session",
            field=models.ForeignKey(
                blank=True,
                db_column="session_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_attempts",
                to="MockAdmin.testsession",
            ),
        ),
        migrations.AddField(
            model_name="userquestionattempt",
            name="time_taken_seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userquestionattempt",
            name="is_correct",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userquestionattempt",
            name="question",
            field=models.ForeignKey(
                db_column="question_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_attempts",
                to="MockAdmin.question",
            ),
        ),
        migrations.AddIndex(
            model_name="userquestionattempt",
            index=models.Index(
                fields=["session"], name="user_questi_session_7f3aa6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userquestionattempt",
            index=models.Index(
                fields=["session", "question"], name="user_questi_session_6a8b29_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="userquestionattempt",
            table="user_question_attempts",
        ),
    ]
