# Generated by Django 5.2 on 2026-04-25 08:43

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0012_statuspost_shared_via"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=community.models.get_profile_pic_path,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to=community.models.get_resume_path
            ),
        ),
    ]
