# Generated by Django 5.2 on 2026-05-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0013_alter_userprofile_picture_alter_userprofile_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("like", "Like on your Post"),
                    ("comment", "Comment on your Post"),
                    ("reply", "Reply to your Comment"),
                    ("mention", "Mention in a Post/Comment"),
                    ("follow", "New Follower"),
                    ("connection_request", "Connection Request"),
                    ("connection_accepted", "Connection Accepted"),
                    ("group_join_request", "Group Join Request"),
                    ("group_join_approved", "Group Join Approved"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
