# Generated by Django 5.2 on 2026-06-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0014_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuspost",
            name="privacy_level",
            field=models.CharField(
                choices=[
                    ("public", "Everyone"),
                    ("members", "Registered Members"),
                    ("followers", "My Followers"),
                    ("connections", "Mutual Connections"),
                    ("self", "Only Me"),
                ],
                default="public",
                help_text="Controls who can view this individual post.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="message_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Everyone"),
                    ("members", "Registered Members"),
                    ("followers", "My Followers"),
                    ("connections", "Mutual Connections"),
                    ("self", "Only Me"),
                ],
                default="members",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Everyone"),
                    ("members", "Registered Members"),
                    ("followers", "My Followers"),
                    ("connections", "Mutual Connections"),
                    ("self", "Only Me"),
                ],
                default="public",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Everyone"),
                    ("members", "Registered Members"),
                    ("followers", "My Followers"),
                    ("connections", "Mutual Connections"),
                    ("self", "Only Me"),
                ],
                default="connections",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone_visibility",
            field=models.CharField(
                choices=[
                    ("public", "Everyone"),
                    ("members", "Registered Members"),
                    ("followers", "My Followers"),
                    ("connections", "Mutual Connections"),
                    ("self", "Only Me"),
                ],
                default="connections",
                max_length=12,
            ),
        ),
    ]
