# Generated by Django 5.2 on 2026-06-04 11:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0015_statuspost_privacy_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statuspost",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                help_text="Automated hashtag storage for fast topic searches.",
                null=True,
                size=None,
            ),
        ),
    ]
