# Generated by Django 5.2 on 2026-06-04 12:10

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0016_statuspost_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="statuspost",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["tags"], name="community_s_tags_e24366_gin"
            ),
        ),
    ]
