# Generated by Django 5.2 on 2026-06-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_message_media_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "community_follow",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.AlterModelOptions(
            name="messagereaction",
            options={},
        ),
    ]
